### ISSUE TITLE
CommonMark instead of parsedown

### ISSUE THREAD

**Issue by dakira** [codex-project/codex#5]
Hey, since the world is agreeing on a standard that has a great PHP implementation by the phpleague and a [Laravel 5 wrapper](https://github.com/GrahamCampbell/Laravel-Markdown), why not use it?

**Comment by kaidesu** [comment]
Because we're using GitHub-flavored markdown.

In the end though it doesn't really matter - parsing content is modular in design through the use of `filters`. One can easily swap out for Commonmark if they so desire.

See the config file here:
https://github.com/codex-project/codex/blob/master/config/codex.php#L80

And filters provided out of the box:
https://github.com/codex-project/codex/tree/master/src/Filters

**Comment by dakira** [comment]
Thanks for clearing that up.
